const actions = {
  ADD_TASK: "ADD_TASK",
  REMOVE_TASK: "REMOVE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  REMOVE_ALL_TASKS: "REMOVE_ALL_TASKS",
  SET_TASKS: "SET_TASKS",
  SET_EDIT_TASK: "SET_EDIT_TASK",
  SET_IS_LOADING: "SET_IS_LOADING",
  ADD_DELETED_TASK: "ADD_DELETED_TASK",
  RESTORE_DELETED_TASK: "RESTORE_DELETED_TASK",
};

export default actions;
